{
  "schemaGroupSerialized" : {
    "type" : "SchemaGroup",
    "actionList" : [ {
      "type" : "MousePointAction",
      "actionBootType" : "RELEASE_MIDDLE_MOUSE_BUTTON",
      "point" : "(823;213)",
      "image" : null,
      "threshold" : 90.0
    } ],
    "groupName" : "Grupa",
    "numberOfIterations" : "1"
  },
  "localSettings" : {
    "stopActionsKeys" : [ ],
    "runActionsKeys" : [ ],
    "endpointName" : ""
  },
  "orgFile" : null,
  "applicationVersion" : "${APPLICATION_VERSION}"
}