package com.patres.automation.keyboard

import java.awt.event.KeyEvent

enum class KeyboardKey(
        val keyValues: List<Int>,
        val keyName: String = KeyEvent.getKeyText(keyValues.first())
) {
    ENTER(listOf(KeyEvent.VK_ENTER)),
    BACK_SPACE(listOf(KeyEvent.VK_BACK_SPACE)),
    TAB(listOf(KeyEvent.VK_TAB)),
    CANCEL(listOf(KeyEvent.VK_CANCEL)),
    CLEAR(listOf(KeyEvent.VK_CLEAR)),
    SHIFT(listOf(KeyEvent.VK_SHIFT)),
    CONTROL(listOf(KeyEvent.VK_CONTROL)),
    ALT(listOf(KeyEvent.VK_ALT)),
    RIGHT_ALT(listOf(KeyEvent.VK_CONTROL, KeyEvent.VK_ALT), "Right Alt"),
    PAUSE(listOf(KeyEvent.VK_PAUSE)),
    CAPS_LOCK(listOf(KeyEvent.VK_CAPS_LOCK)),
    ESCAPE(listOf(KeyEvent.VK_ESCAPE)),
    SPACE(listOf(KeyEvent.VK_SPACE)),
    PAGE_UP(listOf(KeyEvent.VK_PAGE_UP)),
    PAGE_DOWN(listOf(KeyEvent.VK_PAGE_DOWN)),
    END(listOf(KeyEvent.VK_END)),
    HOME(listOf(KeyEvent.VK_HOME)),

    LEFT(listOf(KeyEvent.VK_LEFT)),
    UP(listOf(KeyEvent.VK_UP)),
    RIGHT(listOf(KeyEvent.VK_RIGHT)),
    DOWN(listOf(KeyEvent.VK_DOWN)),

    COMMA(listOf(KeyEvent.VK_COMMA)),
    MINUS(listOf(KeyEvent.VK_MINUS)),
    PERIOD(listOf(KeyEvent.VK_PERIOD)),
    SLASH(listOf(KeyEvent.VK_SLASH)),

    KEY_0(listOf(KeyEvent.VK_0)),
    KEY_1(listOf(KeyEvent.VK_1)),
    KEY_2(listOf(KeyEvent.VK_2)),
    KEY_3(listOf(KeyEvent.VK_3)),
    KEY_4(listOf(KeyEvent.VK_4)),
    KEY_5(listOf(KeyEvent.VK_5)),
    KEY_6(listOf(KeyEvent.VK_6)),
    KEY_7(listOf(KeyEvent.VK_7)),
    KEY_8(listOf(KeyEvent.VK_8)),
    KEY_9(listOf(KeyEvent.VK_9)),

    SEMICOLON(listOf(KeyEvent.VK_SEMICOLON)),
    EQUALS(listOf(KeyEvent.VK_EQUALS)),

    A(listOf(KeyEvent.VK_A)),
    B(listOf(KeyEvent.VK_B)),
    C(listOf(KeyEvent.VK_C)),
    D(listOf(KeyEvent.VK_D)),
    E(listOf(KeyEvent.VK_E)),
    F(listOf(KeyEvent.VK_F)),
    G(listOf(KeyEvent.VK_G)),
    H(listOf(KeyEvent.VK_H)),
    I(listOf(KeyEvent.VK_I)),
    J(listOf(KeyEvent.VK_J)),
    K(listOf(KeyEvent.VK_K)),
    L(listOf(KeyEvent.VK_L)),
    M(listOf(KeyEvent.VK_M)),
    N(listOf(KeyEvent.VK_N)),
    O(listOf(KeyEvent.VK_O)),
    P(listOf(KeyEvent.VK_P)),
    Q(listOf(KeyEvent.VK_Q)),
    R(listOf(KeyEvent.VK_R)),
    S(listOf(KeyEvent.VK_S)),
    T(listOf(KeyEvent.VK_T)),
    U(listOf(KeyEvent.VK_U)),
    V(listOf(KeyEvent.VK_V)),
    W(listOf(KeyEvent.VK_W)),
    X(listOf(KeyEvent.VK_X)),
    Y(listOf(KeyEvent.VK_Y)),
    Z(listOf(KeyEvent.VK_Z)),

    OPEN_BRACKET(listOf(KeyEvent.VK_OPEN_BRACKET)),
    BACK_SLASH(listOf(KeyEvent.VK_BACK_SLASH)),
    CLOSE_BRACKET(listOf(KeyEvent.VK_CLOSE_BRACKET)),

    NUMPAD0(listOf(KeyEvent.VK_NUMPAD0)),
    NUMPAD1(listOf(KeyEvent.VK_NUMPAD1)),
    NUMPAD2(listOf(KeyEvent.VK_NUMPAD2)),
    NUMPAD3(listOf(KeyEvent.VK_NUMPAD3)),
    NUMPAD4(listOf(KeyEvent.VK_NUMPAD4)),
    NUMPAD5(listOf(KeyEvent.VK_NUMPAD5)),
    NUMPAD6(listOf(KeyEvent.VK_NUMPAD6)),
    NUMPAD7(listOf(KeyEvent.VK_NUMPAD7)),
    NUMPAD8(listOf(KeyEvent.VK_NUMPAD8)),
    NUMPAD9(listOf(KeyEvent.VK_NUMPAD9)),
    MULTIPLY(listOf(KeyEvent.VK_MULTIPLY)),
    ADD(listOf(KeyEvent.VK_ADD)),

    SEPARATOR(listOf(KeyEvent.VK_SEPARATOR)),

    SUBTRACT(listOf(KeyEvent.VK_SUBTRACT)),
    DECIMAL(listOf(KeyEvent.VK_DECIMAL)),
    DIVIDE(listOf(KeyEvent.VK_DIVIDE)),
    DELETE(listOf(KeyEvent.VK_DELETE)),
    NUM_LOCK(listOf(KeyEvent.VK_NUM_LOCK)),
    SCROLL_LOCK(listOf(KeyEvent.VK_SCROLL_LOCK)),

    F1(listOf(KeyEvent.VK_F1)),
    F2(listOf(KeyEvent.VK_F2)),
    F3(listOf(KeyEvent.VK_F3)),
    F4(listOf(KeyEvent.VK_F4)),
    F5(listOf(KeyEvent.VK_F5)),
    F6(listOf(KeyEvent.VK_F6)),
    F7(listOf(KeyEvent.VK_F7)),
    F8(listOf(KeyEvent.VK_F8)),
    F9(listOf(KeyEvent.VK_F9)),
    F10(listOf(KeyEvent.VK_F10)),
    F11(listOf(KeyEvent.VK_F11)),
    F12(listOf(KeyEvent.VK_F12)),

    PRINTSCREEN(listOf(KeyEvent.VK_PRINTSCREEN)),
    INSERT(listOf(KeyEvent.VK_INSERT)),
    HELP(listOf(KeyEvent.VK_HELP)),
    META(listOf(KeyEvent.VK_META)),
    BACK_QUOTE(listOf(KeyEvent.VK_BACK_QUOTE)),
    QUOTE(listOf(KeyEvent.VK_QUOTE)),

    WINDOWS(listOf(KeyEvent.VK_WINDOWS)),
    CONTEXT_MENU(listOf(KeyEvent.VK_CONTEXT_MENU));


}