{
  "schemaGroupSerialized" : {
    "type" : "SchemaGroup",
    "actionList" : [ {
      "type" : "DelayAction",
      "actionBootType" : "DELAY",
      "timeContainer" : {
        "value" : "123",
        "type" : "SECONDS"
      }
    } ],
    "groupName" : "Grupa",
    "numberOfIterations" : "1",
    "turnOn" : true
  },
  "localSettings" : {
    "stopActionsKeys" : [ ],
    "runActionsKeys" : [ ],
    "endpointName" : ""
  },
  "orgFile" : null,
  "applicationVersion" : "${APPLICATION_VERSION}"
}