{
  "schemaGroupSerialized" : {
    "type" : "SchemaGroup",
    "actionList" : [ {
      "type" : "TextFieldAction",
      "actionBootType" : "SCROLL_WHEEL_UP",
      "value" : "4"
    } ],
    "groupName" : "Grupa",
    "numberOfIterations" : "1",
    "turnOn" : true
  },
  "localSettings" : {
    "stopActionsKeys" : [ ],
    "runActionsKeys" : [ ],
    "endpointName" : ""
  },
  "orgFile" : null,
  "applicationVersion" : "${APPLICATION_VERSION}"
}