{
  "schemaGroupSerialized" : {
    "type" : "SchemaGroup",
    "actionList" : [ {
      "type" : "BrowserAction",
      "actionBootType" : "PASTE_TEXT_FROM_FILE",
      "path" : "${PROJECT_PATH}\\src\\test\\resources\\test-files\\test-file.txt"
    } ],
    "groupName" : "Grupa",
    "numberOfIterations" : "1"
  },
  "localSettings" : {
    "stopActionsKeys" : [ ],
    "runActionsKeys" : [ ],
    "endpointName" : ""
  },
  "orgFile" : null,
  "applicationVersion" : "${APPLICATION_VERSION}"
}