{
  "schemaGroupSerialized" : {
    "type" : "SchemaGroup",
    "actionList" : [ {
      "type" : "MousePointAction",
      "actionBootType" : "CLICK_RIGHT_MOUSE_BUTTON",
      "point" : "V(154;135)",
      "image" : null,
      "threshold" : 90.0,
      "ignoreIfNotFound" : false
    } ],
    "groupName" : "Grupa",
    "numberOfIterations" : "1",
    "turnOn" : true
  },
  "localSettings" : {
    "stopActionsKeys" : [ ],
    "runActionsKeys" : [ ],
    "endpointName" : ""
  },
  "orgFile" : null,
  "applicationVersion" : "${APPLICATION_VERSION}"
}